#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_TIMEOUT 150
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "AWDDG/bvZ0wj"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

